### ISSUE TITLE
Please Exclude Compilation Product

### ISSUE THREAD

**Issue by blinfoldking** [adf-telkomuniv/AiLibrary#1]
first of all, this is a great library, but i think it would be great if you could exclude compilation product such as *.class, it will make the repository less cluttered and reduced in size. 😄

**Comment by blinfoldking** [comment]
i would like to suggest usage of [.gitignore](https://git-scm.com/docs/gitignore) in this repository

**Comment by adf-telkomuniv** [comment]
Ah yes, thank you
it is a really old project that I finally decided to just open it 😅
